# Generated by Django 4.1.5 on 2023-01-24 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companie',
            new_name='Company',
        ),
    ]
