# Generated by Django 4.1.5 on 2023-02-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_rename_companie_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('salary_per_hour', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hours_per_week', models.IntegerField()),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
